import Navbar from "@/components/Navbar";
import { Inter } from "next/font/google";
import "./globals.css";
import { RecoilWrapper } from "./RecoilWrapper";
import { useRecoilState } from "recoil";
import { theme } from "@/atoms";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: `winprn's blog`,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <RecoilWrapper>
        <body
          className={`${inter.className} bg-[#FAFAFA] text-[#71717A] dark:bg-black dark:text-slate-300`}
        >
          <div className="relative mx-auto flex min-h-screen w-full max-w-7xl flex-col items-center bg-white px-8 dark:bg-[#18181B]">
            <header className="relative z-50 mb-4 h-20 w-full p-2">
              <Navbar />
            </header>
            {children}
            <footer className="mb-4 mt-10">
              <p className="text-sm">
                &copy; 2023 winprn. All rights reserved.
              </p>
            </footer>
          </div>
        </body>
      </RecoilWrapper>
    </html>
  );
}
